version: v3
teleport:
  nodename: localhost
  data_dir: /var/lib/teleport
  join_params:
    token_name: 750f4c0954b2ffe411e8196001b42b5c
    method: token
  proxy_server: teleport-cluster.bomdiagato.xyz:3080
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "no"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
