- name: Add node_exporter job to Prometheus config
  become: true
  lineinfile:
    path: /etc/prometheus/prometheus.yml
    line: |
      # New Node Exporter job
        - job_name: "node-exporter_{{ item }}"
          static_configs:
            - targets: ["{{ item }}:9100"]
    insertafter: EOF
  loop: "{{ groups['node_exporter_servers'] }}"

- name: Add kminion job to Prometheus config
  become: true
  lineinfile:
    path: /etc/prometheus/prometheus.yml
    line: |
      # New Kminion job
        - job_name: "kminion_{{ item }}"
          static_configs:
            - targets: ["{{ item }}:8080"]
    insertafter: EOF
  loop: "{{ groups['kminion_servers'] }}"

- name: Reload systemd configuration and start Prometheus service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    enabled: yes
    state: restarted
